// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7LqkN5gtVMLQcc7lN5jqWibxcgBe5eLo',
    appId: '1:533899571849:android:e61f491c55529999bc4c58',
    messagingSenderId: '533899571849',
    projectId: 'porte-chai-835f3',
    storageBucket: 'porte-chai-835f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUnHi4VYrXwdJiS4QHm828awGgqfS64LM',
    appId: '1:533899571849:ios:7ae8212ff26c3374bc4c58',
    messagingSenderId: '533899571849',
    projectId: 'porte-chai-835f3',
    storageBucket: 'porte-chai-835f3.appspot.com',
    androidClientId: '533899571849-l9fb41i9ke8ml23pa4e1rv04oeasoh8r.apps.googleusercontent.com',
    iosClientId: '533899571849-al436rd4c23k7tek67ti5lrh9sbilk7h.apps.googleusercontent.com',
    iosBundleId: 'com.example.porteChai',
  );
}
